.\" Manpage for rx.
.\" Contact contact@digitalleaves.com for comments or help.
.TH man 1 "28 Apr 2020" "1.0" "rx man page"
.SH NAME
rx \- regular expression match / tester
.SH SYNOPSIS
rx [-[hirPpEeo]] [-x] REGEXP [-f] SOURCE
.SH DESCRIPTION
Command line testing application for "c++ standard regex implemnetation", aka "#include <regex>".
.SH OPTIONS
    -h, --help
        Displays a friendly help message.

    -i, --ignore_case
        ignore case

    -r, --version
        Displays the software version.

    -P, --pretty
        Pretty output.

    -p, --no-pretty
        No pretty output.

    -E, --extendend
        Extendend regular expression.

    -e, --non-extendend
        Not extendend regular expressions.

    -o, --options 
        Use stl regular expression options.

    -f, --file 
        Use file input.

    -x, --regex_file
        Use file for expression.

.SH BUGS
No known bugs.
.SH AUTHOR
Brian Preston (brian8181@gmail.com)